### Basic Array Operations:

- Create a 1D array containing integers from 0 to 9.
- Create a 2D array (matrix) with dimensions 3x3.
- Access specific elements of the arrays using indexing.
- Perform element-wise arithmetic operations (+, -, *, /) on arrays.

In [2]:
import numpy as np

In [3]:
# Create a 1D array containing integers from 0 to 9.
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_1d)

array_2d = np.arange(10)
print(array_2d)

#Create a 2D array (matrix) with dimensions 3x3.
matrix_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(matrix_2d)

print(matrix_2d.ndim)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:


#Access specific elements of the arrays using indexing.
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

print (array1[0,1:3])


In [ ]:
#Perform element-wise arithmetic operations (+, -, *, /) on arrays.

# Create two 2D arrays for demonstration
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
division_result = array1 / array2

print("Array 1:")
print(array1)

print("Array 2:")
print(array2)

print("Addition Result:")
print(addition_result)

print("Subtraction Result:")
print(subtraction_result)

print("Multiplication Result:")
print(multiplication_result)

print("Division Result:")
print(division_result)