### Basic Array Operations:

- Create a 1D array containing integers from 0 to 9.
- Create a 2D array (matrix) with dimensions 3x3.
- Access specific elements of the arrays using indexing.
- Perform element-wise arithmetic operations (+, -, *, /) on arrays.

In [13]:
import numpy as np

In [14]:
# Create a 1D array containing integers from 0 to 9.
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array_1d)

array_2d = np.arange(10)
print(array_2d)

#Create a 2D array (matrix) with dimensions 3x3.
matrix_2d = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
print(matrix_2d)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#Access specific elements of the arrays using indexing.
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

print (array1[0,1:3])


[2 3]


In [15]:
#Perform element-wise arithmetic operations (+, -, *, /) on arrays.

# Create two 2D arrays for demonstration
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])

# Element-wise addition
addition_result = array1 + array2

# Element-wise subtraction
subtraction_result = array1 - array2

# Element-wise multiplication
multiplication_result = array1 * array2

# Element-wise division
division_result = array1 / array2

print("Array 1:")
print(array1)

print("Array 2:")
print(array2)

print("Addition Result:")
print(addition_result)

print("Subtraction Result:")
print(subtraction_result)

print("Multiplication Result:")
print(multiplication_result)

print("Division Result:")
print(division_result)

Array 1:
[[1 2 3]
 [4 5 6]]
Array 2:
[[10 20 30]
 [40 50 60]]
Addition Result:
[[11 22 33]
 [44 55 66]]
Subtraction Result:
[[ -9 -18 -27]
 [-36 -45 -54]]
Multiplication Result:
[[ 10  40  90]
 [160 250 360]]
Division Result:
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
