### Reshaping and Resizing:
- Flatten a multi-dimensional array using .flatten() or .ravel().
- Change the shape of an array using np.reshape().


In [5]:
import numpy as np

In [6]:
# Creating a 2D array
multi_dim_array = np.array([[1, 2, 3],
                            [4, 5, 6]])

# Using .flatten() to flatten the array
flattened_array1 = multi_dim_array.flatten()

# Using .ravel() to flatten the array
flattened_array2 = multi_dim_array.ravel()

print("Original array:\n", multi_dim_array)
print("Flattened array using .flatten():\n", flattened_array1)
print("Flattened array using .ravel():\n", flattened_array2)

Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array using .flatten():
 [1 2 3 4 5 6]
Flattened array using .ravel():
 [1 2 3 4 5 6]


Both `.flatten()` and `.ravel()` will return a flattened copy of the original array. However, there's a subtle difference between them:

`.flatten()`: This method returns a new flattened array, making a deep copy of the data. Any changes you make to the flattened array will not affect the original array.
`.ravel()`: This method also returns a flattened array, but it might return a view of the original data if possible. If a view is returned, changes you make to the flattened array will affect the original array as well.

In [14]:
# RESHAPE

# Creating a 1D array
array = np.array([1, 2, 3, 4, 5, 6])
array2 = np.array([1, 2, 3, 4, 5, 6], ndmin=5)
print (array2)

# Reshaping the array to a 2D array with 2 rows and 3 columns
reshaped_array = np.reshape(array, (2, 3))
reshaped_array2 = np.reshape(array, (-1, 2))



print("Original array:\n", array)
print("Reshaped array:\n", reshaped_array)
print("Reshaped array:\n", reshaped_array2)

[[[[[1 2 3 4 5 6]]]]]
Original array:
 [1 2 3 4 5 6]
Reshaped array:
 [[1 2 3]
 [4 5 6]]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


It's important to note that the total number of elements in the original array must match the total number of elements in the reshaped array. If you're unsure about the shape of one of the dimensions and want to automatically infer it based on the other dimension, you can use -1 as a placeholder. NumPy will calculate the appropriate value for the dimension marked as -1.

In [4]:
# Creating a 1D array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the array to a 2D array with an unknown number of rows and 2 columns
reshaped_array = np.reshape(array, (-1, 2))

print("Original array:\n", array)
print("Reshaped array:\n", reshaped_array)

Original array:
 [1 2 3 4 5 6]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
