### Working with Data:
- Load data from a CSV file into a NumPy array.
- Extract specific columns or rows from the data.


In [2]:
import numpy as np

In [3]:
# Load data from CSV file into a NumPy array
file_path = "data.csv"
data_array = np.genfromtxt(file_path, delimiter=',')

print("Loaded data array:\n", data_array)

Loaded data array:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


You can use NumPy's array indexing to extract specific columns or rows from a data array. Here are examples of how to do that:

Let's assume you have the following data in a NumPy array:

```python
import numpy as np

data_array = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
```

**Extract Specific Columns:**

To extract specific columns, you can use array indexing with the `[:, columns]` syntax. For example, to extract the second column:

```python
second_column = data_array[:, 1]
print("Second column:", second_column)
```

This will output:

```
Second column: [2 5 8]
```

**Extract Specific Rows:**

To extract specific rows, you can use array indexing with the `[rows, :]` syntax. For example, to extract the first and third rows:

```python
selected_rows = data_array[[0, 2], :]
print("Selected rows:\n", selected_rows)
```

This will output:

```
Selected rows:
 [[1 2 3]
 [7 8 9]]
```

**Extract Specific Rows and Columns:**

You can also use both row and column indexing to extract specific submatrices. For example, to extract a submatrix consisting of the first and third rows and the second column:

```python
submatrix = data_array[[0, 2], 1]
print("Submatrix:\n", submatrix)
```

This will output:

```
Submatrix:
 [2 8]
```

By using these indexing techniques, you can easily extract specific columns, rows, or submatrices from your data array. Remember that indexing is zero-based in Python and NumPy, so the first element is at index 0.