### Array Initialization:
- Create an array of zeros with a specified shape.
- Create an array of ones with a specified shape.
- Create an identity matrix using np.eye().


In [2]:
import numpy as np

In [5]:
#Create an array of zeros with a specified shape.
zeros_array = np.zeros((3, 4))

print(zeros_array)

#Create an array of ones with a specified shape.
ones_array = np.ones((3,4))
print(ones_array)

#Create an identity matrix using np.eye().
identity_matrix = np.eye(3)
print(identity_matrix)

# Create a 3x3 array filled with 5
filled_array = np.full((3, 3), 5)

print("Filled array:\n", filled_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Filled array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
