### Array Initialization:
- Create an array of zeros with a specified shape.
- Create an array of ones with a specified shape.
- Create an identity matrix using np.eye().


In [2]:
import numpy as np

In [4]:
#Create an array of zeros with a specified shape.
zeros_array = np.zeros((3, 4))

print(zeros_array)

#Create an array of ones with a specified shape.
ones_array = np.ones((3,4))
print(ones_array)

#Create an identity matrix using np.eye().
identity_matrix = np.eye(3)
print(identity_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/var/folders/hs/z4bycjqn4k95m4dwvckm33mc0000gn/T/ipykernel_35534/574844296.py:15: RuntimeWarning: divide by zero encountered in true_divide
  result = np.divide(arr, identity_matrix)
