### Array Slicing and Indexing:
- Slice and reshape arrays to create new views.
- Use boolean indexing to filter elements based on conditions.


In [4]:
import numpy as np

In [6]:
# Create a 1D array
array_1d = np.array([0, 1, 2, 3, 4, 5])
print(array_1d[3])

3


In [7]:
# Create a 1D array
array_1d = np.array([0, 1, 2, 3, 4, 5])

# Access individual elements using indexing
element_at_index_2 = array_1d[2]  # Access the element at index 2 (value: 2)
element_at_index_4 = array_1d[4]  # Access the element at index 4 (value: 4)

print("Array:", array_1d)
print("Element at index 2:", element_at_index_2)
print("Element at index 4:", element_at_index_4)

array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing examples
sliced_array = array_1d[2:6]# Elements from index 2 to 5 (inclusive)
every_second_element = array_1d[::2]  # Every second element
reverse_array = array_1d[::-1]      # Reverse the array

print("Array:", array_1d)
print("Sliced array:", sliced_array)
print("Every second element:", every_second_element)
print("Reversed array:", reverse_array)

Array: [0 1 2 3 4 5]
Element at index 2: 2
Element at index 4: 4
Array: [0 1 2 3 4 5 6 7 8 9]
Sliced array: [2 3 4 5]
Every second element: [0 2 4 6 8]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [8]:
# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indexing and slicing for 2D arrays
element_at_1_1 = matrix[1, 1]    # Access the element at row 1, column 1 (value: 5)
row_2 = matrix[1, :]             # Access the second row
column_3 = matrix[:, 2]          # Access the third column

print("Matrix:")
print(matrix)
print("Element at (1, 1):", element_at_1_1)
print("Row 2:", row_2)
print("Column 3:", column_3)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1, 1): 5
Row 2: [4 5 6]
Column 3: [3 6 9]


In [9]:
#Use boolean indexing to filter elements based on conditions.

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a boolean array based on a condition
condition = array_1d > 5

# Use boolean indexing to filter elements based on the condition
filtered_elements = array_1d[condition]

print("Original array:", array_1d)
print("Boolean condition:", condition)
print("Filtered elements:", filtered_elements)

# Create a boolean array based on multiple conditions
condition = (array_1d > 3) & (array_1d < 8)

# Use boolean indexing to filter elements based on the combined condition
filtered_elements = array_1d[condition]

print("Original array:", array_1d)
print("Boolean condition:", condition)
print("Filtered elements:", filtered_elements)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Boolean condition: [False False False False False  True  True  True  True  True]
Filtered elements: [ 6  7  8  9 10]
Original array: [ 1  2  3  4  5  6  7  8  9 10]
Boolean condition: [False False False  True  True  True  True False False False]
Filtered elements: [4 5 6 7]
