### Mathematical Functions
- Apply mathematical functions to arrays.
- Calculate the mean, median, and standard deviation of an array.


In [2]:
import numpy as np

In [5]:
numbers = np.array([4, 9, 16])
numbers2 = np.array([2, 2, 2])

arr2 = numbers * numbers2

print(arr2)

[ 4 18 48]


In [6]:
numbers = np.array([4, 9, 16])
# Calculate the square root of each number
sqrt_values = np.sqrt(numbers)

print(sqrt_values)  # Output: [2. 3. 4.]

# Calculate the natural logarithm of each number
log_values = np.log(numbers)

print(log_values)  # Output: [0.         0.69314718 2.30258509]

abs_values = np.abs(numbers)

print(abs_values)  # Output: [4 9 16]

# Raise each number to the power of 3
power_values = np.power(numbers, 3)

print(power_values)

[2. 3. 4.]
[1.38629436 2.19722458 2.77258872]
[ 4  9 16]
[  64  729 4096]


In [7]:
#Calculate the mean, median, and standard deviation of an array.

# Create an array of numbers
numbers = np.array([10, 20, 30, 40, 50])

# Calculate the mean
mean_value = np.mean(numbers)

print(mean_value)  # Output: 30.0

# Calculate the median
median_value = np.median(numbers)


# Calculate the standard deviation
std_deviation = np.std(numbers)

print(std_deviation)  # Output: 15.81...


print(median_value)  # Output: 30.0

30.0
14.142135623730951
30.0
