### Array Manipulation:
- Transpose a matrix using np.transpose() or .T.
- Concatenate arrays vertically and horizontally using np.concatenate().
- Stack arrays vertically and horizontally using np.vstack() and np.hstack().


In [1]:
import numpy as np

In [4]:
# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Transpose the matrix using np.transpose()
transposed_matrix = np.transpose(matrix)

print("Original Matrix:\n", matrix)
print("Transposed Matrix:\n", transposed_matrix)

# Transpose the matrix using the .T attribute
transposed_matrix = matrix.T

print("Transposed Matrix with T attriute:\n", transposed_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]
Transposed Matrix with T attriute:
 [[1 4]
 [2 5]
 [3 6]]


In [9]:
# Create two arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Concatenate arrays vertically using np.concatenate()
vertical_concatenated = np.concatenate((array1, array2), axis=0)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Vertically Concatenated:\n", vertical_concatenated)

# Concatenate arrays horizontally using np.concatenate()
horizontal_concatenated = np.concatenate((array1, array2), axis=1)

print("Horizontally Concatenated:\n", horizontal_concatenated)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Vertically Concatenated:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontally Concatenated:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [11]:

# Stack arrays vertically and horizontally using np.vstack() and np.hstack().
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

stack = np.stack((array1, array2), axis=1)

# Stacking arrays using np.stack()
print(stack)

# Stacking arrays vertically using np.vstack()
vertical_stack = np.vstack((array1, array2))

print("Stacked vertically:")
print(vertical_stack)

# Stacking arrays horizontally using np.hstack()
horizontal_stack = np.hstack((array1, array2))

print("\nStacked horizontally:")
print(horizontal_stack)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
Stacked vertically:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Stacked horizontally:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
