### Array Aggregation:
- Sum the elements of an array using np.sum().
- Find the maximum and minimum values using `np.max()` and `np.min()`

In [2]:
import numpy as np

In [3]:
# Creating a 2D array
my_2d_array = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Aggregating the sum of array elements along different axes using np.sum()
total_sum = np.sum(my_2d_array)  # Sum of all elements
row_sums = np.sum(my_2d_array, axis=1)  # Sum along rows
column_sums = np.sum(my_2d_array, axis=0)  # Sum along columns

print("2D Array:\n", my_2d_array)
print("Total sum:", total_sum)
print("Sum along rows:", row_sums)
print("Sum along columns:", column_sums)

2D Array:
 [[1 2 3]
 [4 5 6]]
Total sum: 21
Sum along rows: [ 6 15]
Sum along columns: [5 7 9]


In this example, the np.sum() function is used to perform array aggregation:

total_sum: Calculates the sum of all elements in the 2D array.
row_sums: Calculates the sum of elements along each row (axis 1).
column_sums: Calculates the sum of elements along each column (axis 0).
You can adjust the axis parameter to aggregate along different dimensions as needed.

Remember that aggregation functions like `np.sum()` can be applied to arrays with any number of dimensions, not just 2D arrays. The axis parameter allows you to control which axes to aggregate along, making it versatile for handling multi-dimensional arrays.

In [4]:
#Find the maximum and minimum values using np.max() and np.min().

# Creating an example array
my_array = np.array([5, 2, 8, 1, 9, 3])

# Finding the maximum and minimum values using np.max() and np.min()
max_value = np.max(my_array)
min_value = np.min(my_array)

print("Array:", my_array)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

# Creating a 2D array
my_2d_array = np.array([[5, 2, 8],
                        [1, 9, 3]])

max_values_row = np.max(my_2d_array, axis=1)  # Max along rows
min_values_column = np.min(my_2d_array, axis=0)  # Min along columns

print("2D Array:\n", my_2d_array)
print("Maximum values along rows:", max_values_row)
print("Minimum values along columns:", min_values_column)

Array: [5 2 8 1 9 3]
Maximum value: 9
Minimum value: 1
2D Array:
 [[5 2 8]
 [1 9 3]]
Maximum values along rows: [8 9]
Minimum values along columns: [1 2 3]
