### This is a DEMO file

first code in jupyter notebook

In [3]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4])
print (arr)

arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print (arr2)

[0 1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [2]:
arr2 = np.arange(5)
print (arr2)

[0 1 2 3 4]
