In [2]:
import numpy as np

### 1
Create a 1D array of numbers from 0 to 9  

#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### 2
Create a 3×3 numpy array of all True’s

In [5]:
arr = np.full((3, 3), True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### 3

Extract all odd numbers from array

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
result = arr[arr % 2 == 1]
print(result)

[1 3 5 7 9]


### 4

Replace all odd numbers in arr with -1

In [17]:
arr = np.arange(10)
arr[arr %2 ==1 ] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 5

Replace all odd numbers in arr with -1 without changing arr

In [18]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6

Convert a 1D array to a 2D array with 2 rows

In [20]:
arr = np.arange(10)
arr = arr.reshape(2, -1)

arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 7

Stack arrays a and b vertically

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#1
arr = np.concatenate([a, b], axis=0)
print (arr)

#2
arr1 = np.vstack([a, b])
print (arr1)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### 8

Stack the arrays a and b horizontally.

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

arr = np.concatenate((a, b), axis=1)
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 9

Create the following pattern without hardcoding. Use only numpy functions and the below input array a

a = np.array([1,2,3])`

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [34]:
a = np.array([1,2,3])
print (np.tile(a, 3))
b =np.concatenate((np.repeat(a, 3), np.tile(a, 3)))

b

[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

###  10 

Get the common items between a and b

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [39]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

arr = np.intersect1d(a, b)
arr


array([2, 4])

### 11

From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Desired Output:

array([1,2,3,4])

In [40]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### 12

Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

#> (array([1, 3, 5, 7]),)


In [41]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

### 13

Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])



In [50]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a>=5) & (a<=10)]

# Method 2
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 3
index = np.where(np.logical_and(a>=5, a<=10))
a[index]


array([ 6,  9, 10])

### 14

Convert the function maxx that works on two scalars, to work on two arrays.
```
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
```

a = np.array([5, 7, 9, 8, 6, 4, 5])  
b = np.array([6, 3, 4, 8, 9, 7, 1])  
pair_max(a, b)  
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])  


In [51]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])  
b = np.array([6, 3, 4, 8, 9, 7, 1]) 

pair_max = np.vectorize(maxx, otypes='f')
pair_max(a, b) 

array([6., 7., 9., 8., 9., 7., 5.], dtype=float32)

### 15

Swap columns 1 and 2 in the array arr

Input  
arr = np.arange(9).reshape(3,3)  
arr  

In [56]:
arr = np.arange(9).reshape(3,3)

arr[:, (1,0,2)]  


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 16 

Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)


In [57]:
arr = np.arange(9).reshape(3,3)

arr[(1,0,2), :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### 17 

Reverse the rows of a 2D array arr

In [64]:
arr = np.arange(9).reshape(3,3)

arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 18

Reverse the columns of a 2D array arr.

arr = np.arange(9).reshape(3,3)

In [61]:
arr = np.arange(9).reshape(3,3)

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 19

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.


In [65]:
and_arr = np.random.uniform(5,10, size=(5,3))

and_arr

array([[6.38935747, 9.06815863, 6.71161005],
       [9.02287196, 6.97466808, 8.59144964],
       [6.54759188, 5.75701068, 8.28187727],
       [5.40231411, 8.15675258, 7.57889423],
       [9.63525448, 6.39166295, 5.20069684]])

### 21

Print or show only 3 decimal places of the numpy array rand_arr.

np.random.random((5,3))

In [68]:
arr = np.random.random((5,3))
np.set_printoptions(precision=3)

arr

array([[0.358, 0.653, 0.121],
       [0.204, 0.003, 0.177],
       [0.572, 0.875, 0.185],
       [0.291, 0.574, 0.456],
       [0.065, 0.356, 0.613]])

### 22 

Pretty print rand_arr by suppressing the scientific notation (like 1e10)


In [80]:
# Reset printoptions to default
np.set_printoptions(suppress=False)

rand_arr = np.random.random([3,3])/1e3
print(rand_arr)



[[1.736e-04 9.666e-04 9.570e-04]
 [5.980e-04 7.313e-04 3.404e-04]
 [9.206e-05 4.635e-04 5.087e-04]]


### 23

Import the iris dataset keeping the text intact.

In [88]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

### 25

Extract the text column species from the 1D iris imported in previous question.

In [92]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)
print(iris_1d.shape)

species = np.array([row[4] for row in iris_1d])
species[:5]

(150, 5)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

### 26

Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [94]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=object)

# Solution:
# Method 1: Convert each row to a list and get the first 4 items
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

# Alt Method 2: Import only the first 4 columns from source url
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

### 27

How to find the position of missing values in numpy array?

In [102]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print (iris_2d[:4])
print("Number of missing values: \n", np.isnan(iris_2d[:, :]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, :])))


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 nan 0.2]
 [4.6 3.1 1.5 0.2]]
Number of missing values: 
 20
Position of missing values: 
 (array([  2,  35,  46,  49,  50,  55,  60,  61,  63,  70,  71,  76,  77,
        96,  99, 107, 121, 126, 130, 146]), array([2, 0, 2, 0, 0, 0, 2, 2, 1, 3, 2, 1, 0, 1, 1, 0, 3, 1, 2, 2]))


### 28

Filter the rows of iris_2d that has iris_2d (3rd column) > 1.5 and iris_2d (1st column) < 5.0

In [109]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

### 29

How to drop rows that contain a missing value from a numpy array?

In [121]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.1, 3.7, 1.5, 0.4],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3

### 30

How to find if a given array has any null values?

In [124]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.any(np.isnan(iris_2d))

False

### 31

How to replace all missing values with 0 in a numpy array?

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

### 32 

How to find the count of unique values in a numpy array?
Find the unique values and the count of unique values in iris's 5th column

In [125]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species = np.array([row.tolist()[4] for row in iris])
np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'),
 array([50, 50, 50]))

### 33

How to convert a numeric to a categorical (text) array?

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

Less than 3 --> 'small'  
3-5 --> 'medium'  
'>=5 --> 'large'


In [135]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

print(iris[:4, 2])
# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]


[b'1.4' b'1.4' b'1.3' b'1.5']


['small', 'small', 'small', 'small']

### 34

How to create a new column from existing columns of a numpy array

Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [163]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris_2d, volume])
